CREATE TABLE IF NOT EXISTS users
(
    id    INT     NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR NOT NULL,
    email VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS items
(
    id           INT     NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR NOT NULL,
    description  VARCHAR NOT NULL,
    is_available BOOLEAN NOT NULL,
    owner_id     INT     NOT NULL REFERENCES users (id),
    request_id   INT
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         INT                         NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id    INT                         NOT NULL REFERENCES items (id),
    booker_id  INT                         NOT NULL REFERENCES users (id),
    status     VARCHAR                     NOT NULL
);